version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: asknicely_jingyu
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - asknicely_net

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: asknicely_jingyu
      DB_USER: root
      DB_PASS: 123456
      DB_CHARSET: utf8mb4
    networks:
      - asknicely_net

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - asknicely_net

volumes:
  mysql_data:

networks:
  asknicely_net:
    driver: bridge
